#!/bin/bash

# gitlab-ci-multi-runner data directory
DATA_DIR="/etc/gitlab-runner"
CONFIG_FILE=${CONFIG_FILE:-$DATA_DIR/config.toml}
# custom certificate authority path
CA_CERTIFICATES_PATH=${CA_CERTIFICATES_PATH:-$DATA_DIR/certs/ca.crt}
LOCAL_CA_PATH="/usr/local/share/ca-certificates/ca.crt"

update_ca() {
  echo "Updating CA certificates..."
  cp "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}"
  update-ca-certificates --fresh >/dev/null
}

if [ -f "${CA_CERTIFICATES_PATH}" ]; then
  # update the ca if the custom ca is different than the current
  cmp --silent "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}" || update_ca
fi

if ! grep 'token' ${DATA_DIR}/config.toml
then
  echo "Runner is not configured... registering"
  if ! [ -z "$DOCKER_VOLUMES" ]
  then
    VOLUMES_ARG=`echo "$DOCKER_VOLUMES" | awk 'BEGIN { RS = "," }; { printf "--docker-volumes %s ", $0 }'`
    unset DOCKER_VOLUMES
  fi
  gitlab-runner register $VOLUMES_ARG
else
  echo "Runner is already configured"
fi

# launch gitlab-ci-multi-runner passing all arguments
exec gitlab-ci-multi-runner "$@"

